In [4]:
# question 1) Create a null vector of size 10 but the fifth value which is 1.
import numpy as np
(np.arange(10) == 4).astype(int)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [14]:
# question 2) Create a vector with values ranging from 10 to 49.
v = np.arange(10,50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [15]:
# question 3) Create a 3x3 matrix with values ranging from 0 to 8
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
# question 4) Find indices of non-zero elements from [1,2,0,0,4,0]
A = [1,2,0,0,4,0];
np.nonzero(A)

(array([0, 1, 4]),)

In [19]:
# question 5) Create a 10x10 array with random values and find the minimum and maximum values.
x = np.random.rand(10,10)
mini = x.min()
maxi = x.max()
print(mini,maxi)

0.03756000825831807 0.9747551860859002


In [20]:
# question 6) Create a random vector of size 30 and find the mean value.

x = np.random.rand(30)
mean_val = x.mean()
print(mean_val)

0.5045854466689292
